version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/code

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - setup_remote_docker
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-
      - run: |
          ./gradlew clean build && \
          docker build -t dius-shopping:latest . 

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
